name: The Nice Paper Co.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82994
title: The Nice Paper Co.
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8fc449'
    - '#0c1230'
    - '#127131'
    - '#939498'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.4080805864650756
  rhythmicContrast: 0.5
purpose: []
